name: Build and Release

on:
  push:
    tags:
      - v*

env:
  PACKAGE_NAME: luci-app-tailscale

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout source
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup OpenWrt SDK
      uses: openwrt/gh-action-sdk@v5
      env:
        ARCH: x86_64
        NO_DEFAULT_FEEDS: 1

    - name: Build Package
      run: |
        set -eux
        cd openwrt

        mkdir -p package/custom
        ln -s "$GITHUB_WORKSPACE" package/custom/${PACKAGE_NAME}

        echo "CONFIG_USE_APK=y" >> .config
        make defconfig

        make package/${PACKAGE_NAME}/compile V=s

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: openwrt/bin/packages/*.apk
        generate_release_notes: true